#Tạo mới
POST http://localhost:5000/api/categories/create
Content-Type: application/json
Authorization: Bearer {token}

body: {
    image: string,
    name: string
}
req: 
    200: {
        success: boolean,
        message: string
    }
    400: {
        success: boolean,
        message: string
    }


#Lấy tất cả category
GET http://localhost:5000/api/categories
Content-Type: application/json
Authorization: Bearer {token}

body: none
req: 
    200: {
        success: boolean,
        message: string,
        categories: [
            items: {
                uid: string,
                image: string,
                name: string
            }
        ]
    }
    400: {
        success: boolean,
        message: string
    }


#Cập nhật thông tin
PUT http://localhost:5000/api/categories/update
Content-Type: application/json
Authorization: Bearer {token}

body: {
    uid: string,
    image: string,
    name: string
}
req: 
    200: {
        success: boolean,
        message: string,
        category: {
            uid: string,
            image: string,
            name: string
        }
    }
    400: {
        success: boolean,
        message: string
    }


#Xóa thông tin
DELETE http://localhost:5000/api/categories/delete
Content-Type: application/json
Authorization: Bearer {token}

body: { categoryUID: string }
req: 
    200: {
        success: boolean,
        message: string,
    }
    400: {
        success: boolean,
        message: string
    }