#Gửi mã xác thực qua email và nhận mã xác thực
POST http://localhost:5000/api/emails/send
Content-Type: application/json
Authorization: Bearer {token}

body: { email: string }
req:
    200: {
        success: boolean,
        message: string,
        code: string
    }
    400: {
        success: boolean,
        error: string
    }